# Generated by Django 5.2.1 on 2025-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_year", models.CharField(blank=True, max_length=20)),
                ("imdb_rating", models.FloatField(blank=True, null=True)),
                ("directors", models.TextField(blank=True)),
                ("cast", models.TextField(blank=True)),
                ("plot_summary", models.TextField(blank=True)),
            ],
        ),
    ]
