# Generated by Django 5.2.1 on 2025-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
